version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lastlifts-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: lastlifts-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    build:
      context: ./
      dockerfile: DB_Dockerfile
    image: mysql
    container_name: lastlifts-mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

