services:
  app:
    build:
      context: ../
      dockerfile: ./docker/DockerfileApp
    container_name: lastlifts-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www
  nginx:
    image: nginx:1.19-alpine
    container_name: lastlifts-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
  db:
    build:
      context: ../
      dockerfile: ./docker/DockerfileDb
    image: mysql:8.0.32
    container_name: lastlifts-mysql
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  mysql_data:
